/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every sellable variant
         * @description Returns the storefront catalog. Inactive variants are left out; sold out ones are listed with available set to false, so the shopper sees them without being able to buy.
         */
        get: operations["CatalogController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{sku}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a single variant by sku
         * @description Returns one variant with its current stock, for the product detail screen.
         */
        get: operations["CatalogController_find"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Place an order
         * @description Validates the payload, decrements stock for every item and records the order. Stock is only taken when the whole order can be served, so a partial purchase never happens.
         */
        post: operations["CheckoutController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a placed order
         * @description Returns the order as it was recorded, with sku, name and price frozen at purchase time.
         */
        get: operations["OrdersController_find"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorDetail: {
            /**
             * @description Path of the field that failed validation, dotted for nested fields.
             * @example items.0.quantity
             */
            field: string;
            /**
             * @description Human readable explanation, written in Brazilian Portuguese.
             * @example Informe ao menos uma unidade.
             */
            message: string;
        };
        ErrorBody: {
            /**
             * @description Machine readable error code. Clients branch on this, never on the message.
             * @example INSUFFICIENT_STOCK
             * @enum {string}
             */
            code: "INVALID_BODY" | "MISSING_IDEMPOTENCY_KEY" | "ROUTE_NOT_FOUND" | "SKU_NOT_FOUND" | "ORDER_NOT_FOUND" | "INSUFFICIENT_STOCK" | "VALIDATION_FAILED" | "SERVICE_UNAVAILABLE" | "INTERNAL_ERROR";
            /**
             * @description Human readable message, written in Brazilian Portuguese and safe to display.
             * @example Não temos essa quantidade em estoque.
             */
            message: string;
            /** @description Field level failures, present only when the error is a validation failure. */
            details?: components["schemas"]["ErrorDetail"][];
        };
        ResponseMeta: {
            /**
             * @description Identifier assigned to the request, echoed back for correlation in logs.
             * @example req_9f2c1a4b7d3e5081
             */
            requestId: string;
            /**
             * @description Moment the response was built, in ISO 8601.
             * @example 2026-08-09T12:00:00.000Z
             */
            timestamp: string;
        };
        ErrorResponse: {
            /**
             * @description Always null when the request failed.
             * @example null
             */
            data: {
                [key: string]: unknown;
            } | null;
            /** @description What went wrong. */
            error: components["schemas"]["ErrorBody"];
            /** @description Metadata attached to every response. */
            meta: components["schemas"]["ResponseMeta"];
        };
        SuccessResponse: {
            /** @description Payload of the request. Its shape changes per route. */
            data: {
                [key: string]: unknown;
            } | null;
            /**
             * @description Always null when the request succeeded.
             * @example null
             */
            error: {
                [key: string]: unknown;
            } | null;
            /** @description Metadata attached to every response. */
            meta: components["schemas"]["ResponseMeta"];
        };
        VariantResponse: {
            /**
             * @description Stock keeping unit. Identifies the variant in every other endpoint.
             * @example CAP-SCRAPBOOK-IP16-AIS-TRA
             */
            sku: string;
            /**
             * @description Commercial name shown on the storefront, written in Brazilian Portuguese.
             * @example Floral Scrapbook · iPhone 16
             */
            name: string;
            /**
             * @description Long description shown on the product detail, written in Brazilian Portuguese.
             * @example Colagem de flores prensadas, fitas e polaroides sobre fundo bege, com espaço para nome e fotos.
             */
            description: string;
            /**
             * @description Unit price as an integer amount of cents. R$ 79,90 is 7990.
             * @example 7990
             */
            priceCents: number;
            /**
             * @description Unit price already formatted as Brazilian currency, so the client never divides by 100.
             * @example R$ 79,90
             */
            formattedPrice: string;
            /**
             * @description Units currently on hand. Zero means sold out, not hidden.
             * @example 12
             */
            availableQty: number;
            /**
             * @description Whether the variant can be bought right now, meaning availableQty is above zero.
             * @example true
             */
            available: boolean;
            /**
             * @description Absolute URL of the full size image, built from IMAGES_BASE_URL.
             * @example http://localhost:3333/images/cap-scrapbook-ip16-ais-tra.jpg
             */
            imageUrl: string;
            /**
             * @description Absolute URL of the thumbnail, used by the storefront listing.
             * @example http://localhost:3333/images/cap-scrapbook-ip16-ais-tra-thumb.jpg
             */
            thumbUrl: string;
        };
        OrderItemResponse: {
            /**
             * @description Stock keeping unit frozen at purchase time, so the order survives catalog edits.
             * @example CAP-SCRAPBOOK-IP16-AIS-TRA
             */
            sku: string;
            /**
             * @description Product name frozen at purchase time, written in Brazilian Portuguese.
             * @example Floral Scrapbook · iPhone 16
             */
            name: string;
            /**
             * @description Units bought of this variant.
             * @example 2
             */
            quantity: number;
            /**
             * @description Unit price frozen at purchase time, as an integer amount of cents.
             * @example 7990
             */
            unitPriceCents: number;
            /**
             * @description Line total in cents, meaning unitPriceCents multiplied by quantity.
             * @example 15980
             */
            subtotalCents: number;
        };
        OrderResponse: {
            /**
             * @description Human readable order number, the reference the customer quotes to support.
             * @example CCS-2026-000417
             */
            number: string;
            /**
             * @description Where the order stands. Only PENDING can still move to another status.
             * @example CONFIRMED
             * @enum {string}
             */
            status: "PENDING" | "CONFIRMED" | "CANCELLED" | "FAILED";
            /** @description Lines of the order, with sku, name and price frozen at purchase time. */
            items: components["schemas"]["OrderItemResponse"][];
            /**
             * @description Sum of every line total, as an integer amount of cents.
             * @example 15980
             */
            subtotalCents: number;
            /**
             * @description Shipping in cents. Flat 1990, or 0 when subtotalCents is at least 19900.
             * @example 1990
             */
            shippingCents: number;
            /**
             * @description Discount in cents. Always 0 in this delivery, there is no coupon yet.
             * @example 0
             */
            discountCents: number;
            /**
             * @description What the customer pays: subtotalCents plus shippingCents minus discountCents.
             * @example 17970
             */
            totalCents: number;
            /**
             * @description Moment the order was placed, in ISO 8601.
             * @example 2026-08-09T12:00:03.104Z
             */
            createdAt: string;
        };
        CheckoutItemDto: {
            /**
             * @description Stock keeping unit of the variant being bought, as returned by GET /products.
             * @example CAP-SCRAPBOOK-IP16-AIS-TRA
             */
            sku: string;
            /**
             * @description How many units of this variant to buy.
             * @example 2
             */
            quantity: number;
        };
        RecipientDto: {
            /**
             * @description Full name of whoever receives the order.
             * @example Ana Beatriz Nogueira
             */
            name: string;
            /**
             * @description Brazilian CPF, eleven digits with no punctuation.
             * @example 39053344705
             */
            taxId: string;
            /**
             * @description Contact email, where the order confirmation is sent.
             * @example ana.nogueira@example.com
             */
            email: string;
            /**
             * @description Contact phone with area code. Optional.
             * @example 11987654321
             */
            phone?: string;
            /**
             * @description Brazilian postal code, eight digits with no dash.
             * @example 01310930
             */
            zipCode: string;
            /**
             * @description Street name of the delivery address.
             * @example Avenida Paulista
             */
            street: string;
            /**
             * @description Street number. Text, because addresses like 1578-A exist.
             * @example 1578
             */
            number: string;
            /**
             * @description Apartment, block or reference point. Optional.
             * @example Apto 92, torre B
             */
            complement?: string;
            /**
             * @description Neighbourhood of the delivery address.
             * @example Bela Vista
             */
            district: string;
            /**
             * @description City of the delivery address.
             * @example São Paulo
             */
            city: string;
            /**
             * @description State as the two letter Brazilian abbreviation.
             * @example SP
             */
            state: string;
        };
        CreateCheckoutDto: {
            /** @description Lines of the order. Each sku may appear only once, with its own quantity. */
            items: components["schemas"]["CheckoutItemDto"][];
            /** @description Who receives the order and where it is delivered. */
            recipient: components["schemas"]["RecipientDto"];
        };
        OrderEventResponse: {
            /**
             * @description Status the order held before this event. Null on the event that created it.
             * @example PENDING
             * @enum {string|null}
             */
            previousStatus: "PENDING" | "CONFIRMED" | "CANCELLED" | "FAILED" | null;
            /**
             * @description Status the order moved to.
             * @example CONFIRMED
             * @enum {string}
             */
            newStatus: "PENDING" | "CONFIRMED" | "CANCELLED" | "FAILED";
            /**
             * @description What caused the transition, such as the checkout flow or an operator action.
             * @example checkout
             */
            source: string;
            /**
             * @description Explanation of the transition, written in Brazilian Portuguese.
             * @example Estoque reservado e pedido confirmado.
             */
            message: string;
            /**
             * @description Moment the transition happened, in ISO 8601.
             * @example 2026-08-09T12:00:03.117Z
             */
            createdAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CatalogController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The catalog, one entry per active variant. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: components["schemas"]["VariantResponse"][];
                    };
                };
            };
            /** @description Unexpected failure. The cause is logged under meta.requestId. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CatalogController_find: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stock keeping unit, as listed by GET /products. */
                sku: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested variant. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: components["schemas"]["VariantResponse"];
                    };
                };
            };
            /** @description SKU_NOT_FOUND. Unknown sku, or a variant that is no longer active. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected failure. The cause is logged under meta.requestId. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CheckoutController_create: {
        parameters: {
            query?: never;
            header: {
                /** @description Client generated key that identifies this purchase attempt. Retrying with the same key returns the original order instead of buying twice. */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCheckoutDto"];
            };
        };
        responses: {
            /** @description Idempotent repeat. This Idempotency-Key had already been used, so the order created the first time is returned unchanged and no new stock was taken. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: components["schemas"]["OrderResponse"];
                    };
                };
            };
            /** @description Order placed. Stock was decremented and the idempotency key was recorded. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: components["schemas"]["OrderResponse"];
                    };
                };
            };
            /** @description MISSING_IDEMPOTENCY_KEY. The request arrived without the Idempotency-Key header. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description SKU_NOT_FOUND. One of the requested skus is unknown or no longer active. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description INSUFFICIENT_STOCK. Someone else took the last units while this order was open. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description VALIDATION_FAILED. The payload broke a field rule; details lists every failure. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected failure. The cause is logged under meta.requestId. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description SERVICE_UNAVAILABLE. Injected failure, used to exercise the retry path. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    OrdersController_find: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order number handed back by POST /checkout. */
                number: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: components["schemas"]["OrderResponse"];
                    };
                };
            };
            /** @description ORDER_NOT_FOUND. No order carries this number. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected failure. The cause is logged under meta.requestId. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
