export type CatalogPattern = {
  code: string;
  name: string;
  slug: string;
  description: string;
  basePriceCents: number;
};

export type CatalogVariant = {
  sku: string;
  patternCode: string;
  device: string;
  material: string;
  color: string;
  priceCents: number;
  weightGrams: number;
  imageFile: string;
  thumbFile: string;
};

export const CATALOG_PATTERNS: readonly CatalogPattern[] = [
  {
    code: 'SCRAPBOOK',
    name: 'Floral Scrapbook',
    slug: 'floral-scrapbook-case',
    description:
      'Colagem de flores prensadas, fitas e polaroides sobre fundo bege, com espaço para nome e fotos.',
    basePriceCents: 7990,
  },
  {
    code: 'BLOOM',
    name: 'Delicate Bloom',
    slug: 'delicate-bloom',
    description:
      'Ramos de cerejeira em flor sobre fundo rosa claro, com espaço para inicial e nome.',
    basePriceCents: 7990,
  },
  {
    code: 'MAGNOLIA',
    name: 'Rosa Magnólia',
    slug: 'rosa-magnolia-case',
    description: 'Magnólias em rosa e magenta sobre fundo transparente, com espaço para nome.',
    basePriceCents: 10990,
  },
  {
    code: 'BUTTERFLY',
    name: 'Rose Butterfly Line',
    slug: 'rose-butterfly-line',
    description:
      'Borboletas rosadas e flores de haste dourada sobre fundo transparente, com espaço para nome.',
    basePriceCents: 7990,
  },
  {
    code: 'DARKFLORAL',
    name: 'Dark Floral Pattern',
    slug: 'dark-floral-pattern',
    description:
      'Padrão denso de flores laranja e creme com folhagem escura, sobre fundo quase preto.',
    basePriceCents: 7990,
  },
  {
    code: 'CAPPUCCINO',
    name: 'Cappuccino Hearts',
    slug: 'cappuccino-hearts-case',
    description:
      'Corações desenhados em fita marrom translúcida sobre fundo creme, com espaço para inicial.',
    basePriceCents: 10990,
  },
  {
    code: 'LINEART',
    name: 'Lineart Watercolor Flowers',
    slug: 'lineart-watercolor-flowers',
    description:
      'Três flores de haste fina em aquarela pastel sobre fundo bege, com espaço para nome.',
    basePriceCents: 7990,
  },
  {
    code: 'SAFARI',
    name: 'Safari Glam',
    slug: 'safari-glam-case',
    description:
      'Oncinha em caramelo com manchas pretas cravejadas de glitter, com espaço para monograma.',
    basePriceCents: 7990,
  },
  {
    code: 'GARDENIA',
    name: 'Jardim de Gardênias',
    slug: 'jardim-de-gardenias-case',
    description:
      'Gardênias brancas e amarelas com folhagem verde sobre fundo transparente, com espaço para nome.',
    basePriceCents: 7990,
  },
  {
    code: 'HEARTS',
    name: 'Corações Cravejados',
    slug: 'coracoes-cravejados-case',
    description:
      'Corações, frutas e folhas cravejados de glitter colorido sobre fundo transparente.',
    basePriceCents: 7990,
  },
  {
    code: 'BOTANICA',
    name: 'Noite Botânica',
    slug: 'noite-botonica-ia-case',
    description:
      'Flores laranja e amarelas, samambaias, luas e um esquilo sobre fundo marrom escuro.',
    basePriceCents: 7990,
  },
  {
    code: 'SUNRISE',
    name: 'Flora Sunrise',
    slug: 'flora-sunrise',
    description: 'Flores grandes em rosa, azul e laranja preenchendo a capa sobre fundo claro.',
    basePriceCents: 7990,
  },
];

export const CATALOG_VARIANTS: readonly CatalogVariant[] = [
  {
    sku: 'CAP-SCRAPBOOK-IP16-AIS-TRA',
    patternCode: 'SCRAPBOOK',
    device: 'iPhone 16',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 32,
    imageFile: 'cap-scrapbook-ip16-ais-tra.jpg',
    thumbFile: 'cap-scrapbook-ip16-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-SCRAPBOOK-IP15P-AIS-TRA',
    patternCode: 'SCRAPBOOK',
    device: 'iPhone 15 Pro',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 31,
    imageFile: 'cap-scrapbook-ip15p-ais-tra.jpg',
    thumbFile: 'cap-scrapbook-ip15p-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-SCRAPBOOK-IP14-AIS-TRA',
    patternCode: 'SCRAPBOOK',
    device: 'iPhone 14',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 30,
    imageFile: 'cap-scrapbook-ip14-ais-tra.jpg',
    thumbFile: 'cap-scrapbook-ip14-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-SCRAPBOOK-IP13-AIS-TRA',
    patternCode: 'SCRAPBOOK',
    device: 'iPhone 13',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 30,
    imageFile: 'cap-scrapbook-ip13-ais-tra.jpg',
    thumbFile: 'cap-scrapbook-ip13-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-SCRAPBOOK-S24-AIS-TRA',
    patternCode: 'SCRAPBOOK',
    device: 'Galaxy S24',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 29,
    imageFile: 'cap-scrapbook-s24-ais-tra.jpg',
    thumbFile: 'cap-scrapbook-s24-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-BLOOM-IP16-AIS-TRA',
    patternCode: 'BLOOM',
    device: 'iPhone 16',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 32,
    imageFile: 'cap-bloom-ip16-ais-tra.jpg',
    thumbFile: 'cap-bloom-ip16-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-BLOOM-IP15P-AIS-TRA',
    patternCode: 'BLOOM',
    device: 'iPhone 15 Pro',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 31,
    imageFile: 'cap-bloom-ip15p-ais-tra.jpg',
    thumbFile: 'cap-bloom-ip15p-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-BLOOM-IP14-AIS-TRA',
    patternCode: 'BLOOM',
    device: 'iPhone 14',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 30,
    imageFile: 'cap-bloom-ip14-ais-tra.jpg',
    thumbFile: 'cap-bloom-ip14-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-BLOOM-IP13-AIS-TRA',
    patternCode: 'BLOOM',
    device: 'iPhone 13',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 30,
    imageFile: 'cap-bloom-ip13-ais-tra.jpg',
    thumbFile: 'cap-bloom-ip13-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-BLOOM-S24-AIS-TRA',
    patternCode: 'BLOOM',
    device: 'Galaxy S24',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 29,
    imageFile: 'cap-bloom-s24-ais-tra.jpg',
    thumbFile: 'cap-bloom-s24-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-MAGNOLIA-IP16-AIS-TRA',
    patternCode: 'MAGNOLIA',
    device: 'iPhone 16',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 10990,
    weightGrams: 32,
    imageFile: 'cap-magnolia-ip16-ais-tra.jpg',
    thumbFile: 'cap-magnolia-ip16-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-MAGNOLIA-IP15P-AIS-TRA',
    patternCode: 'MAGNOLIA',
    device: 'iPhone 15 Pro',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 10990,
    weightGrams: 31,
    imageFile: 'cap-magnolia-ip15p-ais-tra.jpg',
    thumbFile: 'cap-magnolia-ip15p-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-MAGNOLIA-IP14-AIS-TRA',
    patternCode: 'MAGNOLIA',
    device: 'iPhone 14',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 10990,
    weightGrams: 30,
    imageFile: 'cap-magnolia-ip14-ais-tra.jpg',
    thumbFile: 'cap-magnolia-ip14-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-MAGNOLIA-IP13-AIS-TRA',
    patternCode: 'MAGNOLIA',
    device: 'iPhone 13',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 10990,
    weightGrams: 30,
    imageFile: 'cap-magnolia-ip13-ais-tra.jpg',
    thumbFile: 'cap-magnolia-ip13-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-MAGNOLIA-S24-AIS-TRA',
    patternCode: 'MAGNOLIA',
    device: 'Galaxy S24',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 10990,
    weightGrams: 29,
    imageFile: 'cap-magnolia-s24-ais-tra.jpg',
    thumbFile: 'cap-magnolia-s24-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-BUTTERFLY-IP16-AIS-TRA',
    patternCode: 'BUTTERFLY',
    device: 'iPhone 16',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 32,
    imageFile: 'cap-butterfly-ip16-ais-tra.jpg',
    thumbFile: 'cap-butterfly-ip16-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-BUTTERFLY-IP15P-AIS-TRA',
    patternCode: 'BUTTERFLY',
    device: 'iPhone 15 Pro',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 31,
    imageFile: 'cap-butterfly-ip15p-ais-tra.jpg',
    thumbFile: 'cap-butterfly-ip15p-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-BUTTERFLY-IP14-AIS-TRA',
    patternCode: 'BUTTERFLY',
    device: 'iPhone 14',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 30,
    imageFile: 'cap-butterfly-ip14-ais-tra.jpg',
    thumbFile: 'cap-butterfly-ip14-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-BUTTERFLY-IP13-AIS-TRA',
    patternCode: 'BUTTERFLY',
    device: 'iPhone 13',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 30,
    imageFile: 'cap-butterfly-ip13-ais-tra.jpg',
    thumbFile: 'cap-butterfly-ip13-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-BUTTERFLY-S24-AIS-TRA',
    patternCode: 'BUTTERFLY',
    device: 'Galaxy S24',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 29,
    imageFile: 'cap-butterfly-s24-ais-tra.jpg',
    thumbFile: 'cap-butterfly-s24-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-DARKFLORAL-IP16-AIS-TRA',
    patternCode: 'DARKFLORAL',
    device: 'iPhone 16',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 32,
    imageFile: 'cap-darkfloral-ip16-ais-tra.jpg',
    thumbFile: 'cap-darkfloral-ip16-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-DARKFLORAL-IP15P-AIS-TRA',
    patternCode: 'DARKFLORAL',
    device: 'iPhone 15 Pro',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 31,
    imageFile: 'cap-darkfloral-ip15p-ais-tra.jpg',
    thumbFile: 'cap-darkfloral-ip15p-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-DARKFLORAL-IP14-AIS-TRA',
    patternCode: 'DARKFLORAL',
    device: 'iPhone 14',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 30,
    imageFile: 'cap-darkfloral-ip14-ais-tra.jpg',
    thumbFile: 'cap-darkfloral-ip14-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-DARKFLORAL-IP13-AIS-TRA',
    patternCode: 'DARKFLORAL',
    device: 'iPhone 13',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 30,
    imageFile: 'cap-darkfloral-ip13-ais-tra.jpg',
    thumbFile: 'cap-darkfloral-ip13-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-DARKFLORAL-S24-AIS-TRA',
    patternCode: 'DARKFLORAL',
    device: 'Galaxy S24',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 29,
    imageFile: 'cap-darkfloral-s24-ais-tra.jpg',
    thumbFile: 'cap-darkfloral-s24-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-CAPPUCCINO-IP16-AIS-TRA',
    patternCode: 'CAPPUCCINO',
    device: 'iPhone 16',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 10990,
    weightGrams: 32,
    imageFile: 'cap-cappuccino-ip16-ais-tra.jpg',
    thumbFile: 'cap-cappuccino-ip16-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-CAPPUCCINO-IP15P-AIS-TRA',
    patternCode: 'CAPPUCCINO',
    device: 'iPhone 15 Pro',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 10990,
    weightGrams: 31,
    imageFile: 'cap-cappuccino-ip15p-ais-tra.jpg',
    thumbFile: 'cap-cappuccino-ip15p-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-CAPPUCCINO-IP14-AIS-TRA',
    patternCode: 'CAPPUCCINO',
    device: 'iPhone 14',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 10990,
    weightGrams: 30,
    imageFile: 'cap-cappuccino-ip14-ais-tra.jpg',
    thumbFile: 'cap-cappuccino-ip14-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-CAPPUCCINO-IP13-AIS-TRA',
    patternCode: 'CAPPUCCINO',
    device: 'iPhone 13',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 10990,
    weightGrams: 30,
    imageFile: 'cap-cappuccino-ip13-ais-tra.jpg',
    thumbFile: 'cap-cappuccino-ip13-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-CAPPUCCINO-S24-AIS-TRA',
    patternCode: 'CAPPUCCINO',
    device: 'Galaxy S24',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 10990,
    weightGrams: 29,
    imageFile: 'cap-cappuccino-s24-ais-tra.jpg',
    thumbFile: 'cap-cappuccino-s24-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-LINEART-IP16-AIS-TRA',
    patternCode: 'LINEART',
    device: 'iPhone 16',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 32,
    imageFile: 'cap-lineart-ip16-ais-tra.jpg',
    thumbFile: 'cap-lineart-ip16-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-LINEART-IP15P-AIS-TRA',
    patternCode: 'LINEART',
    device: 'iPhone 15 Pro',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 31,
    imageFile: 'cap-lineart-ip15p-ais-tra.jpg',
    thumbFile: 'cap-lineart-ip15p-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-LINEART-IP14-AIS-TRA',
    patternCode: 'LINEART',
    device: 'iPhone 14',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 30,
    imageFile: 'cap-lineart-ip14-ais-tra.jpg',
    thumbFile: 'cap-lineart-ip14-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-LINEART-IP13-AIS-TRA',
    patternCode: 'LINEART',
    device: 'iPhone 13',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 30,
    imageFile: 'cap-lineart-ip13-ais-tra.jpg',
    thumbFile: 'cap-lineart-ip13-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-LINEART-S24-AIS-TRA',
    patternCode: 'LINEART',
    device: 'Galaxy S24',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 29,
    imageFile: 'cap-lineart-s24-ais-tra.jpg',
    thumbFile: 'cap-lineart-s24-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-SAFARI-IP16-AIS-TRA',
    patternCode: 'SAFARI',
    device: 'iPhone 16',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 32,
    imageFile: 'cap-safari-ip16-ais-tra.jpg',
    thumbFile: 'cap-safari-ip16-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-SAFARI-IP15P-AIS-TRA',
    patternCode: 'SAFARI',
    device: 'iPhone 15 Pro',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 31,
    imageFile: 'cap-safari-ip15p-ais-tra.jpg',
    thumbFile: 'cap-safari-ip15p-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-SAFARI-IP14-AIS-TRA',
    patternCode: 'SAFARI',
    device: 'iPhone 14',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 30,
    imageFile: 'cap-safari-ip14-ais-tra.jpg',
    thumbFile: 'cap-safari-ip14-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-SAFARI-IP13-AIS-TRA',
    patternCode: 'SAFARI',
    device: 'iPhone 13',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 30,
    imageFile: 'cap-safari-ip13-ais-tra.jpg',
    thumbFile: 'cap-safari-ip13-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-SAFARI-S24-AIS-TRA',
    patternCode: 'SAFARI',
    device: 'Galaxy S24',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 29,
    imageFile: 'cap-safari-s24-ais-tra.jpg',
    thumbFile: 'cap-safari-s24-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-GARDENIA-IP16-AIS-TRA',
    patternCode: 'GARDENIA',
    device: 'iPhone 16',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 32,
    imageFile: 'cap-gardenia-ip16-ais-tra.jpg',
    thumbFile: 'cap-gardenia-ip16-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-GARDENIA-IP15P-AIS-TRA',
    patternCode: 'GARDENIA',
    device: 'iPhone 15 Pro',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 31,
    imageFile: 'cap-gardenia-ip15p-ais-tra.jpg',
    thumbFile: 'cap-gardenia-ip15p-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-GARDENIA-IP14-AIS-TRA',
    patternCode: 'GARDENIA',
    device: 'iPhone 14',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 30,
    imageFile: 'cap-gardenia-ip14-ais-tra.jpg',
    thumbFile: 'cap-gardenia-ip14-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-GARDENIA-IP13-AIS-TRA',
    patternCode: 'GARDENIA',
    device: 'iPhone 13',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 30,
    imageFile: 'cap-gardenia-ip13-ais-tra.jpg',
    thumbFile: 'cap-gardenia-ip13-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-GARDENIA-S24-AIS-TRA',
    patternCode: 'GARDENIA',
    device: 'Galaxy S24',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 29,
    imageFile: 'cap-gardenia-s24-ais-tra.jpg',
    thumbFile: 'cap-gardenia-s24-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-HEARTS-IP16-AIS-TRA',
    patternCode: 'HEARTS',
    device: 'iPhone 16',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 32,
    imageFile: 'cap-hearts-ip16-ais-tra.jpg',
    thumbFile: 'cap-hearts-ip16-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-HEARTS-IP15P-AIS-TRA',
    patternCode: 'HEARTS',
    device: 'iPhone 15 Pro',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 31,
    imageFile: 'cap-hearts-ip15p-ais-tra.jpg',
    thumbFile: 'cap-hearts-ip15p-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-HEARTS-IP14-AIS-TRA',
    patternCode: 'HEARTS',
    device: 'iPhone 14',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 30,
    imageFile: 'cap-hearts-ip14-ais-tra.jpg',
    thumbFile: 'cap-hearts-ip14-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-HEARTS-IP13-AIS-TRA',
    patternCode: 'HEARTS',
    device: 'iPhone 13',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 30,
    imageFile: 'cap-hearts-ip13-ais-tra.jpg',
    thumbFile: 'cap-hearts-ip13-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-HEARTS-S24-AIS-TRA',
    patternCode: 'HEARTS',
    device: 'Galaxy S24',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 29,
    imageFile: 'cap-hearts-s24-ais-tra.jpg',
    thumbFile: 'cap-hearts-s24-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-BOTANICA-IP16-AIS-TRA',
    patternCode: 'BOTANICA',
    device: 'iPhone 16',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 32,
    imageFile: 'cap-botanica-ip16-ais-tra.jpg',
    thumbFile: 'cap-botanica-ip16-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-BOTANICA-IP15P-AIS-TRA',
    patternCode: 'BOTANICA',
    device: 'iPhone 15 Pro',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 31,
    imageFile: 'cap-botanica-ip15p-ais-tra.jpg',
    thumbFile: 'cap-botanica-ip15p-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-BOTANICA-IP14-AIS-TRA',
    patternCode: 'BOTANICA',
    device: 'iPhone 14',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 30,
    imageFile: 'cap-botanica-ip14-ais-tra.jpg',
    thumbFile: 'cap-botanica-ip14-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-BOTANICA-IP13-AIS-TRA',
    patternCode: 'BOTANICA',
    device: 'iPhone 13',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 30,
    imageFile: 'cap-botanica-ip13-ais-tra.jpg',
    thumbFile: 'cap-botanica-ip13-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-BOTANICA-S24-AIS-TRA',
    patternCode: 'BOTANICA',
    device: 'Galaxy S24',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 29,
    imageFile: 'cap-botanica-s24-ais-tra.jpg',
    thumbFile: 'cap-botanica-s24-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-SUNRISE-IP16-AIS-TRA',
    patternCode: 'SUNRISE',
    device: 'iPhone 16',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 32,
    imageFile: 'cap-sunrise-ip16-ais-tra.jpg',
    thumbFile: 'cap-sunrise-ip16-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-SUNRISE-IP15P-AIS-TRA',
    patternCode: 'SUNRISE',
    device: 'iPhone 15 Pro',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 31,
    imageFile: 'cap-sunrise-ip15p-ais-tra.jpg',
    thumbFile: 'cap-sunrise-ip15p-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-SUNRISE-IP14-AIS-TRA',
    patternCode: 'SUNRISE',
    device: 'iPhone 14',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 30,
    imageFile: 'cap-sunrise-ip14-ais-tra.jpg',
    thumbFile: 'cap-sunrise-ip14-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-SUNRISE-IP13-AIS-TRA',
    patternCode: 'SUNRISE',
    device: 'iPhone 13',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 30,
    imageFile: 'cap-sunrise-ip13-ais-tra.jpg',
    thumbFile: 'cap-sunrise-ip13-ais-tra-thumb.jpg',
  },
  {
    sku: 'CAP-SUNRISE-S24-AIS-TRA',
    patternCode: 'SUNRISE',
    device: 'Galaxy S24',
    material: 'Anti Impacto Slim',
    color: 'Transparente',
    priceCents: 7990,
    weightGrams: 29,
    imageFile: 'cap-sunrise-s24-ais-tra.jpg',
    thumbFile: 'cap-sunrise-s24-ais-tra-thumb.jpg',
  },
];
